export const types = {
  PRELOAD: 'PRELOAD',

  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',

  GET_THREADS: 'GET_THREADS',
  GET_THREAD: 'GET_THREAD',
  UP_VOTE_THREAD_LIST: 'UP_VOTE_THREAD_LIST',
  UP_VOTE_THREAD_DETAIL: 'UP_VOTE_THREAD_DETAIL',
  DOWN_VOTE_THREAD_LIST: 'DOWN_VOTE_THREAD_LIST',
  DOWN_VOTE_THREAD_DETAIL: 'DOWN_VOTE_THREAD_DETAIL',
  NEUTRAL_VOTE_THREAD_LIST: 'NEUTRAL_VOTE_THREAD_LIST',
  NEUTRAL_VOTE_THREAD_DETAIL: 'NEUTRAL_VOTE_THREAD_DETAIL',

  CREATE_COMMENT: 'CREATE_COMMENT',
  UP_VOTE_COMMENT_LIST: 'UP_VOTE_COMMENT_LIST',
  DOWN_VOTE_COMMENT_LIST: 'DOWN_VOTE_COMMENT_LIST',
  NEUTRAL_VOTE_COMMENT_LIST: 'NEUTRAL_VOTE_COMMENT_LIST',

  GET_LEADERBOARDS: 'GET_LEADERBOARDS',
}
